#!/usr/bin/env node
// Generate TypeScript types from the frozen /contracts JSON Schemas.
//
// Zero-dependency (Node stdlib only). Mirrors contracts/gen/go: the JSON Schemas
// under contracts/schemas are the single source of truth for the wire shape, and
// this emits their TypeScript binding. Scope: the schemas the SDKs and dashboard
// need today (common, authorize-request, decision, error). Extend SCHEMA_FILES to
// cover policy.schema.json when the control-plane surface is bound.
//
// Usage:  node contracts/tools/gen-ts.mjs
// Outputs (both, so the layout mirrors gen/go and the SDK vendors a copy):
//   contracts/gen/ts/contractsv1/types.ts
//   sdks/ts/src/contracts/generated.ts
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const SCHEMA_DIR = join(ROOT, "contracts", "schemas");

// Top-level schema files to bind, each -> the exported type name for its root.
const SCHEMA_FILES = [
  { file: "common.schema.json", root: null }, // $defs only
  { file: "authorize-request.schema.json", root: "AuthorizeRequest" },
  { file: "decision.schema.json", root: "Decision" },
  { file: "error.schema.json", root: "Problem" },
];

/** @type {Map<string, string>} name -> emitted declaration */
const decls = new Map();

function load(file) {
  return JSON.parse(readFileSync(join(SCHEMA_DIR, file), "utf8"));
}

// Resolve a $ref to the TypeScript type name it denotes.
function refName(ref) {
  // "#/$defs/Name" or "common.schema.json#/$defs/Name"
  const m = ref.match(/#\/\$defs\/([A-Za-z0-9_]+)$/);
  if (!m) throw new Error(`unsupported $ref: ${ref}`);
  return m[1];
}

function firstSentence(desc) {
  if (!desc) return "";
  const line = desc.split("\n")[0].trim();
  return line.length > 160 ? line.slice(0, 157) + "..." : line;
}

// Convert a schema node to an inline TS type expression.
function tsType(schema, ctxName) {
  if (!schema || typeof schema !== "object") return "unknown";
  if (schema.$ref) return refName(schema.$ref);
  if (Array.isArray(schema.enum)) {
    return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  }
  if (schema.const !== undefined) return JSON.stringify(schema.const);

  const t = schema.type;
  if (t === "string") return "string";
  if (t === "integer" || t === "number") return "number";
  if (t === "boolean") return "boolean";
  if (t === "array") return `${wrapUnion(tsType(schema.items, ctxName))}[]`;
  if (t === "object" || schema.properties) {
    return objectType(schema, ctxName);
  }
  return "unknown";
}

function wrapUnion(expr) {
  return expr.includes("|") ? `(${expr})` : expr;
}

// Build an inline object type `{ a: T; b?: U; [k: string]: unknown }`.
function objectType(schema, ctxName) {
  const props = schema.properties || {};
  const required = new Set(schema.required || []);
  const lines = [];
  for (const [key, propSchema] of Object.entries(props)) {
    const optional = required.has(key) ? "" : "?";
    const doc = firstSentence(propSchema.description);
    if (doc) lines.push(`  /** ${doc} */`);
    lines.push(`  ${safeKey(key)}${optional}: ${tsType(propSchema, ctxName + cap(key))};`);
  }
  // Free-form objects (additionalProperties:true and no declared props) -> record.
  if (schema.additionalProperties === true && lines.length === 0) {
    return "Record<string, unknown>";
  }
  // Known props PLUS open extension (e.g. authorize context, evidence).
  if (schema.additionalProperties === true) {
    lines.push(`  [key: string]: unknown;`);
  }
  return `{\n${lines.join("\n")}\n}`;
}

function safeKey(key) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);

// Emit a top-level named declaration (interface for objects, alias otherwise).
function emitNamed(name, schema) {
  if (decls.has(name)) return;
  const doc = firstSentence(schema.description || schema.title);
  const header = doc ? `/** ${doc} */\n` : "";
  const isObject = (schema.type === "object" || schema.properties) && !schema.enum;
  if (isObject) {
    decls.set(name, `${header}export interface ${name} ${objectType(schema, name)}`);
  } else {
    decls.set(name, `${header}export type ${name} = ${tsType(schema, name)};`);
  }
}

function main() {
  for (const { file, root } of SCHEMA_FILES) {
    const schema = load(file);
    if (schema.$defs) {
      for (const [name, def] of Object.entries(schema.$defs)) emitNamed(name, def);
    }
    if (root) emitNamed(root, schema);
  }

  const banner =
    "// Code generated by contracts/tools/gen-ts.mjs from contracts/schemas. DO NOT EDIT.\n" +
    "//\n" +
    "// The TypeScript binding of the frozen /v1 JSON Schemas -- the single source of\n" +
    "// truth for the wire shape, shared by the SDKs, policy-svc, and the dashboard.\n" +
    "// Money is a string (never a float) to preserve exact precision and a stable\n" +
    "// signing form. Regenerate with: node contracts/tools/gen-ts.mjs\n\n";

  const body = [...decls.values()].join("\n\n") + "\n";
  const out = banner + body;

  for (const target of [
    join(ROOT, "contracts", "gen", "ts", "contractsv1", "types.ts"),
    join(ROOT, "sdks", "ts", "src", "contracts", "generated.ts"),
    join(ROOT, "services", "dashboard", "src", "lib", "contracts", "generated.ts"),
  ]) {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, out, "utf8");
    console.log(`wrote ${target}`);
  }
}

main();
